CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	user_name TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE pictures(
	id SERIAL PRIMARY KEY,
	url TEXT NOT NULL,
	title TEXT,
	user_id INTEGER FOREIGN KEY 
);