CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	user_name TEXT NOT NULL UNIQUE,
	password_digest TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE pictures(
	id SERIAL PRIMARY KEY,
	url TEXT NOT NULL,
	title TEXT,
	user_id INTEGER NOT NULL
);